[package]
name = "pixel_engine_gl"
version = "0.1.0"
authors = ["maix0 <maix522@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = "0.18"
gfx_window_glutin = "*"
glutin ="*"
image ="*"
gfx_device_gl ="*"
parking_lot = "0.10.2"

[dev-dependencies]
rand= "*"

[profile.release]
debug = true


[feature]
addon-2dtransform=[]
