[package]
name = "raycast_world"
version = "0.1.0"
authors = ["Maix0 <maix522@gmail.com>"]

edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixel_engine="*"