[package]
name = "pixel_engine_backend"
version = "0.4.0"
authors = ["maix0 <maix522@gmail.com>"]
edition = "2018"
license = "MIT"
description = "An thin layer around wgpu that allow the modification of a texutre displayed on the screen"
repository = "https://github.com/maix0/pixel_engine"
exclude = ["Cargo.lock"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
webgl= ["wgpu/webgl"]

[dependencies]
wgpu = "0.7.1"
bytemuck = "1.5.1"

[target.'cfg(target_arch="wasm32")'.dependencies]
winit = {version = "0.24.0", features = ["web-sys"]}
getrandom = { version = "0.2", features = ["js"] }


[target.'cfg(not(target_arch="wasm32"))'.dependencies]
winit = "0.24.0"

