[package]
name = "pixel_engine_backend"
version = "0.2.1"
authors = ["maix0 <maix522@gmail.com>"]
edition = "2018"
license = "MIT"
description = "An thin layer around wgpu that allow the modification of a texutre displayed on the screen"
repository = "https://github.com/maix0/pixel_engine"
exclude = ["Cargo.lock"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vulkan = ["wgpu/vulkan"]

[dependencies]
wgpu = "0.5.0"
bytemuck = "1.2.0"

[target.'cfg(target_arch="wasm32")'.dependencies]
winit = {version = "0.22.2", features = ["web-sys"]}

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
winit = "0.22.2"
