[target.x86_64-unknown-linux-gnu]
linker="clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=/nix/store/0fk3jyxyzzyb15fb615f740c0qg242yi-mold-1.6.0/bin/mold",
]

[alias]
xtask="run --package xtask --release --"
